language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("bmi-hw-3"); using Coverage; Codecov.sumbit(process_folder())'
after_success:
